version: "3.8"
services:
  bff:
    container_name: bff
    build: 
      context: ./bff
    restart: always
    ports:
      - "3000:3000"
  
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    restart: always
    ports:
      - "81:80"