version: "3.8"
services:
  bff:
    container_name: bff
    build: 
      context: ./bff
    restart: always
  
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    restart: always