name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  init:
    runs-on: self-hosted
    name: Check changed files
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

  build:
    needs: init
    name: Build and publish frontend
    runs-on: self-hosted
    steps:
      -
        name: Stop
        run: docker compose down
      -
        name: Build services
        run: docker compose up --build -d --force-recreate
      -
        name: Check service
        run: docker ps -a
      - name: run ML model
        run: 
